CMAKE:
    variables:
        CMAKE_BUILD_TYPE: release
        CMAKE_INSTALL_PREFIX: ${/ROOT/project_dir}/install

DOCKER:
    enabled: true
    image: dodo_tutorial:1604
    volume_map:
        ${/ROOT/project_dir}/log: /var/log

ROOT:
    build_dir: ${/ROOT/project_dir}/build/${/CMAKE/variables/CMAKE_BUILD_TYPE}
    src_dir: ${/ROOT/project_dir}/src
    decorators:
        docker: ['cmake', 'docker']
    command_path:
    - - ~/.dodo_commands/
      - default_commands/*
    - - ${/ROOT/src_dir}/extra/dodo_commands
      - tutorial_commands
    version: 1.0.0
